// removed StarFieldShader
// removed AtmosphereShader
// removed SunShader
// removed GalaxyShader
// removed GalaxyStarShader
// removed CosmicWebShader
// removed CMBShader
// removed StarFlareShader
// removed BulkShader
// removed FoamShader
// removed StringShader
// removed WebFilamentShader
// removed MultiverseBubbleShader